[volumes]
main = "../data/main_data"
test = "../data/test_data"

[questions]
q01 = "【Q1】What is your age ?"
q02 = "【Q2】What gender do you identify as ?"
q03 = "【Q3】Which geographical region are you currently working or attending school/university in ?"
q04 = "【Q4】Which geographical region do you most strongly associate with ?"
q05 = "【Q5】What is your job title ?"
q06 = "【Q6】Which group do you belong to ? "
q07 = "【Q7】What is your research type ?"
q08 = "【Q8】How long have you been in this field ?"
q09 = "【Q9】Are you satisfied with your career to date ?"
q10 = "【Q10】How many hours, on average, do you spend on housework, childcare, and caregiving per day ?"
q11 = "【Q11】Did you already sign up for the diversity session in ICRC2023?"
q12 = "【Q12】What do you think about the initiatives on DE&I of your group?"
q13 = "【Q13】What is the percentage of female researcher in your group?"
q14 = "【Q14】What do you think about the percentage above ?"
q15 = "【Q15】Please let us know If your group has any good practice examples related to DE&I ?"
q16 = "【Q16】Please let us know if there is anything your group needs to work on or if your group has any problems related to DE&I."
q17 = "【Q17】What are your thoughts on diversity, equity & inclusion initiatives ?"
q18 = "【Q18】Could you tell us more about your thoughts (agree / disagree) ?"
q19 = "【Q19】When did you first become interested in science ?"
q20 = "【Q20】Do you have any concerns / problems related to DE&I initiatives in science ?"
q21 = "【Q21】What reasons do you think are hindering DE&I initiatives in science ?"
q22 = "【Q22】Comments"


[choices]
age = [
    "10s",
    "20s",
    "30s",
    "40s",
    "50s",
    "60s",
    "70s",
    "80s",
    "90s+",
    "Prefer not to answer",
    ]
gender = [
    "Male",
    "Female",
    "Non-binary",
    "Prefer to self-identify",
    "Prefer not to answer",
    ]

geoscheme = [
    "Europe / North Europe",
    "Europe / West Europe",
    "Europe / Central Europe",
    "Europe / East Europe",
    "Europe / South Europe",
    "Asia / Japan",
    "Asia / Eastern Asia",
    "Asia / South-Eastern Asia",
    "Asia / Southern Asia",
    "Asia / Central Asia",
    "Asia / Western Asia",
    "America / North America",
    "America / Central America",
    "America / South America",
    "Oceania / Oceania",
    "Africa / Northern Africa",
    "Africa / Western Africa",
    "Africa / Middle Africa",
    "Africa / Eastern Africa",
    "Africa / Southern Africa",
    "Prefer not to answer / Prefer not to answer",
]
regional = [
    "Europe",
    "Asia",
    "America",
    "Oceania",
    "Africa",
    "Prefer not to answer",
]
subregional = [
    "North Europe",
    "West Europe",
    "Central Europe",
    "East Europe",
    "South Europe",
    "Japan",
    "Eastern Asia",
    "South-Eastern Asia",
    "Southern Asia",
    "Central Asia",
    "Western Asia",
    "North America",
    "Central America",
    "South America",
    "Oceania",
    "Northern Africa",
    "Western Africa",
    "Middle Africa",
    "Eastern Africa",
    "Southern Africa",
    "Prefer not to answer",
]
job_title = [
    "Undergraduate",
    "Master",
    "Doctrate",
    "Postdoc",
    "Fixed-term staff",
    "Permanent staff",
    "Prefer not to answer",
]
research_group = [
    "CRD: Cosmic-ray physics (Direct)",
    "CRI: Cosmic-ray physics (Indirect)",
    "GA: Gamma-ray astronomy",
    "NU: Neutrino astronomy & physics",
    "SH: Solar & heliospheric physics",
    "DM: Dark-matter physics",
    "MM&GW: Multimessenger & gravitational wave",
    "O&E: Outreach & education",
    "Prefer not to answer",
]
research_field = [
    "Theorist",
    "Experimentalist",
    "Others",
    "Prefer not to answer",
]
research_years = [
    "< 1 year",
    "1 - 3 years",
    "3 - 5 years",
    "5 - 10 yeas",
    "> 10 years",
    "Prefer not to answer",
]
yes_no = [
    "Yes",
    "No",
    "Prefer not to answer",
]
good_poor = [
    "Very Good",
    "Good",
    "Poor",
    "Very Poor",
    "No interest",
    "Prefer not to answer",
]
agree_disagree = [
    "Agree",
    "Disagree",
    "No interest",
    "Prefer not to answer",
]
school = [
    "Pre school",
    "Elementary school",
    "Junior High school",
    "High school",
    "University",
    "Prefer not to answer",
]
cluster = [
    "Cluster1",
    "Cluster2",
    "Cluster3",
    "Cluster4",
    "Others",
]

[[options]]
name = "q01"
title = "Age Group"
description = "【Q1】What is your age?"
type = "categorical"

[[options]]
name = "q02"
title = "Gender Identity"
description = "【Q2】What gender do you identify as?"
type = "categorical"

[[options]]
name = "q03"
title = "Workplace"
description = "【Q3】Which geographical region are you currently working or attending school/university in?"
type = "categorical"

[[options]]
name = "q04"
title = "Birthplace/Hometown"
description = "【Q4】Which geographical region do you most strongly associate with?"
type = "categorical"

[[options]]
name = "q05"
title = "Job Title"
description = "【Q5】What is your job title?"
type = "categorical"

[[options]]
name = "q06"
title = "Research Group"
description = "【Q6】Which group do you belong to?"
type = "categorical"

[[options]]
name = "q07"
title = "Research Field"
description = "【Q7】What is your research type?"
type = "categorical"

[[options]]
name = "q08"
title = "Research Years"
description = "【Q8】How long have you been in this field?"
type = "categorical"

[[options]]
name = "q09"
title = "Career Satisfaction"
description = "【Q9】Are you satisfied with your career to date?"
type = "categorical"

[[options]]
name = "q10"
title = "Hours on housework, childcare, caregiving per day"
description = "【Q10】How many hours, on average, do you spend on housework, childcare, and caregiving per day?"
type = "numerical"

[[options]]
name = "q11"
title = "Diversity Session Signup"
description = "【Q11】Did you already sign up for the diversity session in ICRC2023?"
type = "categorical"

[[options]]
name = "q12_genderbalance"
title = "Group Initiatives on Gender Balance"
description = "【Q12】What do you think about the initiatives on DE&I of your group?"
type = "categorical"

[[options]]
name = "q12_diversity"
title = "Group Initiatives on Diversity"
description = "【Q12】What do you think about the initiatives on DE&I of your group?"
type = "categorical"

[[options]]
name = "q12_equity"
title = "Group Initiatives on Equity"
description = "【Q12】What do you think about the initiatives on DE&I of your group?"
type = "categorical"

[[options]]
name = "q12_inclusion"
title = "Group Initiatives on Inclusion"
description = "【Q12】What do you think about the initiatives on DE&I of your group?"
type = "categorical"

[[options]]
name = "q13"
title = "Percentage of Female Researchers in Group"
description = "【Q13】What is the percentage of female researcher in your group?"
type = "numerical"

[[options]]
name = "q14"
title = "Percentage"
description = "【Q14】What do you think about the percentage above?"
type = "categorical"

[[options]]
name = "q15"
title = "Good Practices"
description = "【Q15】Please let us know If your group has any good practice examples related to DE&I?"
type = "comment"

[[options]]
name = "q16"
title = "Problems"
description = "【Q16】Please let us know if there is anything your group needs to work on or if your group has any problems related to DE&I."
type = "comment"

[[options]]
name = "q17_genderbalance"
title = "Personal Attitude on Gender Balance Initiatives"
description = "【Q17】What are your thoughts on diversity, equity & inclusion initiatives?"
type = "categorical"

[[options]]
name = "q17_diversity"
title = "Personal Attitude on Diversity Initiatives"
description = "【Q17】What are your thoughts on diversity, equity & inclusion initiatives?"
type = "categorical"

[[options]]
name = "q17_equity"
title = "Personal Attitude on Equity Initiatives"
description = "【Q17】What are your thoughts on diversity, equity & inclusion initiatives?"
type = "categorical"

[[options]]
name = "q17_inclusion"
title = "Personal Attitude on Inclusion Initiatives"
description = "【Q17】What are your thoughts on diversity, equity & inclusion initiatives?"
type = "categorical"

[[options]]
name = "q18"
title = "Reasons"
description = "【Q18】Could you tell us more about your thoughts?"
type = "comment"

[[options]]
name = "q19"
title = "Science Interest"
description = "【Q19】When did you first become interested in science?"
type = "categorical"

[[options]]
name = "q20"
title = "Concerns/Problems Related to DE&I Initiatives in Science"
description = "【Q20】Do you have any concerns / problems related to DE&I initiatives in science?"
type = "comment"

[[options]]
name = "q21"
title = "Hindering"
description = "【Q21】What reasons do you think are hindering DE&I initiatives in science?"
type = "comment"

[[options]]
name = "q22"
title = "Comments"
description = "【Q22】Comments"
type = "comment"


[[overview]]
name = "in-person"
total = 1102
male = 852
female = 241
others = 9

[[overview]]
name = "online"
total = 304
male = 220
female = 84
others = 0

[[overview]]
name = "pre-survey"
total = 295
male =  195
female = 90
others = 10
