# Simple workflow for deploying static content to GitHub Pages
name: Check Sphinx Document Build on Branches

on: 
  # Runs on pushes targeting the default branch
  #push:
  #  branches: ["main"]
  # Exclude pushes targetting the main branch
  push:
    branches-ignore:
      - "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Check poetry
        run: |
          poetry --version
          poetry config --list
      - name: Show outdated packages
        run: poetry show --outdated
      - name: Install dependencies
        run: poetry install
      - name: Build Sphinx
        run: |
          cd docs
          poetry run make dirhtml
