# Simple workflow for deploying static content to GitHub Pages
name: Check Sphinx Document Build on Branches

on:
  # Runs on pushes targeting the default branch
  #push:
  #  branches: ["main"]
  # Exclude pushes targetting the main branch
  push:
    branches-ignore:
      - "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"
          enable-cache: true
      - name: Show uv version
        run: uv --version
      - name: Show outdated packages
        run: uv lock --upgrade --dry-run
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Build Sphinx
        run: |
          cd docs
          uv run make dirhtml
